### ISSUE TITLE
Example automation is confusing...

### ISSUE THREAD

**Issue by rv-kip** [mf-social/ps-date-countdown#17]
Having 
```
      - platform: time
        at: '00:00:01'
```
In the example automation means the sensor isn't created until that time. Best to remove that and have the sensor created on HA restart. Helpful for noobs like me.

**Comment by point-4ward** [comment]
Hello,

The very next two lines of the automation cause the automation to trigger also on homeassistant restart, the full trigger copy and pasted exactly from the example on the Readme page... 

```
automation:
  - alias: Reminder - Refresh date countdown sensors
    trigger:
      - platform: time
        at: '00:00:01'
      - platform: homeassistant
        event: start
```
