### ISSUE TITLE
Negative number of years

### ISSUE THREAD

**Issue by SeLLeRoNe** [mf-social/ps-date-countdown#8]
Hi there,

since last update for some reason the "years" attribute became a negative value.
![image](https://user-images.githubusercontent.com/9599441/74262672-9e084380-4cfd-11ea-94da-e2522ef4b8c7.png)

I have checked now the configuration and documentation to see if there was something new I wasn't aware of but it doesn't look like.

The config it's fairly simple, the only difference is that I am using the secret file to store the dates:
```
  - service: python_script.date_countdown
    data:
      name: Andrea
      type: birthday
      date: !secret andrea_birthday
```

Any clue?

Thanks :)
Andrea
